version: "3.3"
services:
  mysqldb:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE= achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - achatdb:/var/lib/mysql

  achat:
    build: ./
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true

    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

volumes:
  achatdb: